export { default as LoginFormComponent } from "./login-form";
export { default as RegisterFormComponent } from "./register-form";
export { default as BorrowFormComponent } from "./borrow-form";
export { default as InformationFormCompent } from "./infor-form";
export { default as BookDetailFormComponent } from "./book-form";
export { default as AddBookFormComponent } from "./add-book-form";
export { default as AddAuthorFormComponent } from "./add-author-form";
export { default as AddCategoryComponent } from "./add-category-form";
export { default as UploadImageFormComponent } from './upload-image-form';